import { CategoryDef } from './types';

export const CATEGORIES: CategoryDef[] = [
  {
    id: 'Makanan',
    name: 'Makanan',
    icon: 'restaurant',
    colorClass: 'border-amber-400 bg-amber-50 text-amber-800',
    bgClass: 'bg-amber-100/70',
    dotClass: 'bg-[#FFD77B] text-[#002115]',
    chipClass: 'bg-[#FFD77B]/20',
    iconColor: 'text-amber-700',
  },
  {
    id: 'Transportasi',
    name: 'Transportasi',
    icon: 'commute',
    colorClass: 'border-blue-400 bg-blue-50 text-blue-800',
    bgClass: 'bg-blue-100/70',
    dotClass: 'bg-[#2650cf] text-white',
    chipClass: 'bg-[#5B7FFF]/20',
    iconColor: 'text-[#2650cf]',
  },
  {
    id: 'Belanja',
    name: 'Belanja',
    icon: 'shopping_bag',
    colorClass: 'border-pink-400 bg-pink-50 text-pink-800',
    bgClass: 'bg-pink-100/70',
    dotClass: 'bg-[#F5A5BE] text-[#39071d]',
    chipClass: 'bg-[#ffd9e2]/80',
    iconColor: 'text-pink-600',
  },
  {
    id: 'Hiburan',
    name: 'Hiburan',
    icon: 'sports_esports',
    colorClass: 'border-indigo-400 bg-indigo-50 text-indigo-800',
    bgClass: 'bg-violet-100/70',
    dotClass: 'bg-[#a46077] text-white',
    chipClass: 'bg-[#ffd9e2]/80',
    iconColor: 'text-violet-600',
  },
  {
    id: 'Kesehatan',
    name: 'Kesehatan',
    icon: 'medical_services',
    colorClass: 'border-emerald-400 bg-emerald-50 text-emerald-800',
    bgClass: 'bg-emerald-100/70',
    dotClass: 'bg-[#7fd5b1] text-emerald-900',
    chipClass: 'bg-[#9df4ce]/30',
    iconColor: 'text-emerald-700',
  },
  {
    id: 'Utilitas',
    name: 'Utilitas',
    icon: 'bolt',
    colorClass: 'border-purple-400 bg-purple-50 text-purple-800',
    bgClass: 'bg-purple-100/70',
    dotClass: 'bg-slate-400 text-white',
    chipClass: 'bg-slate-200/50',
    iconColor: 'text-purple-600',
  },
  {
    id: 'Lainnya',
    name: 'Lainnya',
    icon: 'more_horiz',
    colorClass: 'border-slate-400 bg-slate-50 text-slate-800',
    bgClass: 'bg-slate-100',
    dotClass: 'bg-[#d0dbed] text-slate-700',
    chipClass: 'bg-slate-100',
    iconColor: 'text-slate-600',
  },
  {
    id: 'Pemasukan',
    name: 'Pemasukan',
    icon: 'account_balance_wallet',
    colorClass: 'border-green-400 bg-green-50 text-green-800',
    bgClass: 'bg-emerald-500/10',
    dotClass: 'bg-[#9df4ce] text-emerald-900',
    chipClass: 'bg-[#9df4ce]/30',
    iconColor: 'text-emerald-500',
  },
];

export const getCategoryById = (id: string): CategoryDef | undefined =>
  CATEGORIES.find((c) => c.id === id);
